openapi: 3.0.2

info:
  description: | # Required
    This is a sample server Petstore server.  You can find out more about
        Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For
        this sample, you can use the api key `special-key` to test the authorization filters.
  version: 1.0.0 # Required
  title: Swagger Petstore # Required
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /pet:
    post:
    put:
  /pet/{id}:
    get:
    delete:
  /pet/findByStatus:
    get:
  /store/order:
    post:
    get:
  /store/order/{id}:
    get:
    delete:
  /user:
    post:
    put:
  /user/{id}:
    get:
    delete:
  /user/login:
    get:
  /user/logout:
    get:


